export const CHANNEL_TYPE_NAMES: Readonly<Partial<Record<number, string>>> = {
    0: 'Front Left',
    1: 'Center',
    2: 'Front Right',
    3: 'Front Wide Right',
    4: 'Surround Right',
    5: 'Surround Right', // A
    6: 'Surround Right B',
    7: 'Surround Right C',
    8: 'Surround Back Right',
    9: 'Surround Back Center',
    10: 'Surround Back Left',
    11: 'Surround Left C',
    12: 'Surround Left B',
    13: 'Surround Left', // A
    14: 'Surround Left',
    15: 'Front Wide Left',
    16: 'Center Height',
    17: 'Dolby Front Center',
    18: 'Front Height Right',
    19: 'Top Front Right',
    20: 'Dolby Front Right',
    21: 'Top Middle Right',
    22: 'Top Rear Right',
    23: 'Front Height Wide Right',
    24: 'Surround Height Right',
    25: 'Rear Height Right',
    26: 'Dolby Surround Right',
    27: 'Surround Back Height Right',
    28: 'Dolby Back Right',
    29: 'Dolby Back Center',
    30: 'Dolby Back Left',
    31: 'Surround Back Height Left',
    32: 'Dolby Surround Left',
    33: 'Rear Height Left',
    34: 'Surround Height Left',
    35: 'Front Height Wide Left',
    36: 'Top Rear Left',
    37: 'Top Middle Left',
    38: 'Dolby Front Left',
    39: 'Top Front Left',
    40: 'Front Height Left',
    41: 'Top Surround',
    42: 'Subwoofer',
    43: 'Subwoofer Left',
    44: 'Subwoofer Left',
    45: 'Subwoofer Right',
    46: 'Subwoofer Right',
    47: 'Subwoofer Front',
    48: 'Subwoofer Front',
    49: 'Subwoofer Rear',
    50: 'Subwoofer Rear',
    51: 'Subwoofer Middle',
    52: 'Subwoofer (LFE)',
    53: 'Subwoofer (LFE)',
    54: 'Subwoofer',
    55: 'Subwoofer 2',
    56: 'Subwoofer 3',
    57: 'Subwoofer 4',
    58: 'Subwoofer Front Left',
    59: 'Subwoofer Front Left',
    60: 'Subwoofer Front Right',
    61: 'Subwoofer Front Right',
    62: 'Subwoofer Rear Left',
    63: 'Subwoofer Rear Right',
    64: 'Subwoofer Rear',
    65: 'Subwoofer (LFE)',
};
